### PR TITLE
cleanup build files for casadi addons luamodel and urdfmodel

### PR DESCRIPTION
**Pull request by ju6ge**
See https://github.com/rbdl/rbdl/pull/64 for more information.

### CODE REVIEW

**Comment by PeterQLee** [comment]
Thanks for the changes. It looks like I'm getting a string of compile errors
```
/home/peter/robot/loopwire/rbdl-orb/addons/urdfreader/thirdparty/urdfparser/include/urdf/joint.h:68:8: error: ‘optional’ in namespace ‘std’ does not name a template type
   68 |   std::optional<double> rising;
      |        ^~~~~~~~
/home/peter/robot/loopwire/rbdl-orb/addons/urdfreader/thirdparty/urdfparser/include/urdf/joint.h:68:3: note: ‘std::optional’ is only available from C++17 onwards
   68 |   std::optional<double> rising;
      |   ^~~
/home/peter/robot/loopwire/rbdl-orb/addons/urdfreader/thirdparty/urdfparser/include/urdf/joint.h:69:8: error: ‘optional’ in namespace ‘std’ does not name a template type
   69 |   std::optional<double> falling;
      |        ^~~~~~~~
/home/peter/robot/loopwire/rbdl-orb/addons/urdfreader/thirdparty/urdfparser/include/urdf/joint.h:69:3: note: ‘std::optional’ is only available from C++17 onwards
   69 |   std::optional<double> falling;
      |   ^~~
/home/peter/robot/loopwire/rbdl-orb/addons/urdfreader/thirdparty/urdfparser/include/urdf/joint.h: In member function ‘void urdf::JointCalibration::clear()’:
/home/peter/robot/loopwire/rbdl-orb/addons/urdfreader/thirdparty/urdfparser/include/urdf/joint.h:72:4: error: ‘rising’ was not declared in this scope
   72 |    rising.reset();
      |    ^~~~~~
/home/peter/robot/loopwire/rbdl-orb/addons/urdfreader/thirdparty/urdfparser/include/urdf/joint.h:73:4: error: ‘falling’ was not declared in this scope
   73 |    falling.reset();

```
... etc.

I think the urdfparser requires C++17?  (e.g., https://github.com/PeterQLee/rbdl/blob/master/addons/urdfreader/CMakeLists.txt#L32) Is this enforced in the new CMake configuration?

**Comment by ju6ge** [comment]
Hm I did not get that, maybe my compiler uses a newer version per default. I removed everything that seemed redundant from the original urdfparser CMakeLists.txt. The reasoning being that the urdfparser code gets compiled in the normal rbdl build. But now that I think about it those optionals are in the headers as well. Maybe just re-add the C++17 definition from the original CMakeLists to the urdfparer-casadi CMakeLists.

**Comment by PeterQLee** [comment]
Ok, re-adding the C++17 makes it compile, but it looks like I'm getting a runtime error when I run a test program:
```
undefined symbol: _ZN17RigidBodyDynamics24CalcBodyWorldOrientationERNS_5ModelERKN14RBDLCasadiMath13MX_Xd_dynamicEjb
```
I think the RBDL_USE_CASADI_MATH flag is not getting set. What's the best way of setting this in the rbdl_config.h file?

**Comment by ju6ge** [comment]
The correct way of setting it to make sure it is included in the during the build process. When building rbdl it is copied to `build/include/rbdl` and the casadi version is put into `build/casadi/include/rbdl`. So maybe there is still a include directories definition that leads to the wrong header being first. When linking against casadi from down stream projects the FindCmake file will only find one version of the file due to the different install locations, but during the build it is more messy. The best option I think is to remove all include_directory statements and instead use target_include_directories to specify the includes for every target explicitly. I hope this information helps ;)

**Comment by PeterQLee** [comment]
I fixed the issue by editing the rbdl_config.h.cmake to have the #cmakedefine RBDL_USE_CASADI_MATH definition.

There were also a few headaches because there was an old rbdl_config.h file in main include directory; probably from an old build or something. I think this should be good to go now.

**Comment by ju6ge** [comment]
hm that sound problematic for the normal rbdl … The reason is that RBDL_USE_CASADI_MATH is set to true if the cmake_variable is defined. But that variable should only be true when building the casadi version. rbdl_config.h.cmake is the rbdl_config.h for normal rbdl. For casadi there is rbdl_casadi_config.h.cmake. These files are templated files that are copied by cmake to the build directories. From there it is then later included.

the old rbdl_config.h seems like the bigger culprit here. Anyway RBDL_USE_CASADI_MATH should only every be set in the rbdl_config.h beloging to casadi, never in the rbdl_config.h for normal rbdl.

**Comment by ju6ge** [comment]
How are you building rbdl?

**Comment by ju6ge** [comment]
Ah i see you also renamed the CMake Variable, but if that is working correctly i will have to check later … I don't have time for it right now.

**Pull request merged**
